const List<Town> towns = [
  Town(town: "Batoka", province: "Southern Province"),
  Town(town: "Chadiza", province: "Eastern Province"),
  Town(town: "Chama", province: "Muchinga Province"),
  Town(town: "Chambishi", province: "Copperbelt Province"),
  Town(town: "Chavuma", province: "North Western Province"),
  Town(town: "Chembe", province: "Luapula Province"),
  Town(town: "Chibombo", province: "Central Province"),
  Town(town: "Chienge", province: "Luapula Province"),
  Town(town: "Chifunabuli", province: "Luapula Province"),
  Town(town: "Chikankata", province: "Southern Province"),
  Town(town: "Chilanga", province: "Lusaka Province"),
  Town(town: "Chililabombwe", province: "Copperbelt Province"),
  Town(town: "Chilubi Island", province: "Luapula Province"),
  Town(town: "Chingola", province: "Copperbelt Province"),
  Town(town: "Chinsali", province: "Muchinga Province"),
  Town(town: "Chipata", province: "Eastern Province"),
  Town(town: "Chipili", province: "Luapula Province"),
  Town(town: "Chirundu", province: "Lusaka Province"),
  Town(town: "Chisamba", province: "Central Province"),
  Town(town: "Chisekesi", province: "Southern Province"),
  Town(town: "Choma", province: "Southern Province"),
  Town(town: "Chongwe", province: "Lusaka Province"),
  Town(town: "Gwembe", province: "Southern Province"),
  Town(town: "Isoka", province: "Muchinga Province"),
  Town(town: "Itezhi-Tezhi", province: "Central Province"),
  Town(town: "Itimpi", province: "Copperbelt Province"),
  Town(town: "Kabompo", province: "North Western Province"),
  Town(town: "Kabwe", province: "Central Province"),
  Town(town: "Kafue", province: "Lusaka Province"),
  Town(town: "Kalabo", province: "Western Province"),
  Town(town: "Kalomo", province: "Southern Province"),
  Town(town: "Kalulushi", province: "Copperbelt Province"),
  Town(town: "Kaoma", province: "Western Province"),
  Town(town: "Kapiri Mposhi", province: "Central Province"),
  Town(town: "Kaputa", province: "Luapula Province"),
  Town(town: "Kasama", province: "Northern Province"),
  Town(town: "Kasempa", province: "North Western Province"),
  Town(town: "Katete", province: "Eastern Province"),
  Town(town: "Katima Mulilo", province: "Western Province"),
  Town(town: "Kawambwa", province: "Luapula Province"),
  Town(town: "Kazungula", province: "Southern Province"),
  Town(town: "Kitwe", province: "Copperbelt Province"),
  Town(town: "Livingstone", province: "Southern Province"),
  Town(town: "Luangwa", province: "Lusaka Province"),
  Town(town: "Luanshya", province: "Copperbelt Province"),
  Town(town: "Lubwe", province: "Luapula Province"),
  Town(town: "Lufwanyama", province: "Copperbelt Province"),
  Town(town: "Lukulu", province: "Western Province"),
  Town(town: "Lundazi", province: "Eastern Province"),
  Town(town: "Lusaka", province: "Lusaka Province"),
  Town(town: "Luwingu", province: "Northern Province"),
  Town(town: "Maamba", province: "Southern Province"),
  Town(town: "Macha", province: "Southern Province"),
  Town(town: "Mafinga", province: "Muchinga Province"),
  Town(town: "Mansa", province: "Luapula Province"),
  Town(town: "Masaiti", province: "Copperbelt Province"),
  Town(town: "Mazabuka", province: "Southern Province"),
  Town(town: "Mbala", province: "Northern Province"),
  Town(town: "Mfuwe", province: "Eastern Province"),
  Town(town: "Milenge", province: "Luapula Province"),
  Town(town: "Mkushi", province: "Central Province"),
  Town(town: "Mongu", province: "Western Province"),
  Town(town: "Monze", province: "Southern Province"),
  Town(town: "Mpika", province: "Muchinga Province"),
  Town(town: "Mpongwe", province: "Copperbelt Province"),
  Town(town: "Mporokoso", province: "Northern Province"),
  Town(town: "Mpulungu", province: "Northern Province"),
  Town(town: "Mufulira", province: "Copperbelt Province"),
  Town(town: "Mufumbwe", province: "North Western Province"),
  Town(town: "Mumbwa", province: "Central Province"),
  Town(town: "Mungwi", province: "Northern Province"),
  Town(town: "Mwansabombwe", province: "Luapula Province"),
  Town(town: "Mwense", province: "Luapula Province"),
  Town(town: "Mwinilunga", province: "North Western Province"),
  Town(town: "Nakonde", province: "Muchinga Province"),
  Town(town: "Nalolo", province: "Western Province"),
  Town(town: "Namalundu Gorge", province: "Western Province"),
  Town(town: "Nampundwe", province: "Lusaka Province"),
  Town(town: "Namwala", province: "Southern Province"),
  Town(town: "Nchelenge", province: "Luapula Province"),
  Town(town: "Ndola", province: "Copperbelt Province"),
  Town(town: "Nyimba", province: "Eastern Province"),
  Town(town: "Pemba", province: "Southern Province"),
  Town(town: "Petauke", province: "Eastern Province"),
  Town(town: "Rufunsa", province: "Lusaka Province"),
  Town(town: "Samfya", province: "Luapula Province"),
  Town(town: "Senanga", province: "Western Province"),
  Town(town: "Serenje", province: "Central Province"),
  Town(town: "Sesheke", province: "Western Province"),
  Town(town: "Shangombo", province: "Western Province"),
  Town(town: "Shiwangandu", province: "Muchinga Province"),
  Town(town: "Siavonga", province: "Southern Province"),
  Town(town: "Simba", province: "Eastern Province"),
  Town(town: "Sinazeze", province: "Southern Province"),
  Town(town: "Sinazongwe", province: "Southern Province"),
  Town(town: "Sinda", province: "Eastern Province"),
  Town(town: "Solwezi", province: "North Western Province"),
  Town(town: "Victoria Falls", province: "Southern Province"),
  Town(town: "Zambezi", province: "North Western Province"),
  Town(town: "Zimba", province: "Southern Province"),
];

class Town {
  final String town;
  final String province;

  const Town({this.town, this.province});
}
