/// Flutter icons TolaBustSeat
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TolaBustSeat
///      fonts:
///       - asset: fonts/TolaBustSeat.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TolaBustSeat {
  TolaBustSeat._();

  static const _kFontFam = 'TolaBustSeat';

  static const IconData bus_seat = const IconData(0xe800, fontFamily: _kFontFam);
}
